layout_spectrum: 0.6026159436441958
typography_spectrum: 0.26907389936968684
color:
  brandStrength: 0.560756515013054
  lightness: 0.3106982328463346
  saturation: 0.7904703530948609
  rhythmicContrast: 0.19301662407815456
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
author:
  name: Alejandro
  email: ahepburn03@gmail.com
name: Mola Art Panama
navigation:
  - name: Panama Tours
    url: 'http://pointbtransfers.com/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1a3ea92a-fa39-4d50-8e85-56abc5ff9b75.jpg
title: Beautiful Mola Art and Souvenirs
description: All of the colors of Panama
