typography_spectrum: 0.28522588894702494
color:
  brandStrength: 0.4937106929719448
  lightness: 0.4555791534949094
  saturation: 0.9981307168491185
  rhythmicContrast: 0.2860646895132959
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
layout_spectrum: 0.09469583607278764
author:
  name: Alejandro
  email: ahepburn03@gmail.com
name: Mola Art Panama
navigation:
  - name: Panama Tours
    url: 'http://pointbtransfers.com/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1a3ea92a-fa39-4d50-8e85-56abc5ff9b75.jpg
title: Beautiful Mola Art and Souvenirs
description: All of the colors of Panama
