typography_spectrum: 0.5203479579649866
color:
  brandStrength: 0.9356295268516988
  lightness: 0.4288823469541967
  saturation: 0.9418812026269734
  rhythmicContrast: 0.20127164805307984
  brandColors:
    - '#010101'
    - '#8B7600'
    - '#FEA800'
    - '#006642'
    - '#BDEBFB'
layout_spectrum: 0.7489483740646392
author:
  name: Alejandro
  email: ahepburn03@gmail.com
name: Mola Art Panama
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1a3ea92a-fa39-4d50-8e85-56abc5ff9b75.jpg
title: All of the colors of Panama
description: Beautiful Mola Art and Souvenirs
