layout_spectrum: 0.23701174720190465
typography_spectrum: 0.22478073416277766
color:
  brandStrength: 0.7985152848996222
  lightness: 0.15548728220164776
  saturation: 0.6513871159404516
  rhythmicContrast: 0.4682867641095072
  brandColors:
    - '#85DB18'
    - '#CDE855'
    - '#F5F6D4'
    - '#A7C520'
    - '#493F0B'
author:
  name: Alejandro
  email: ahepburn03@gmail.com
name: Mola Art Panama
navigation:
  - name: Panama Tours
    url: 'http://pointbtransfers.com/'
    type: external
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/1a3ea92a-fa39-4d50-8e85-56abc5ff9b75.jpg
title: Beautiful Mola Art and Souvenirs
description: All of the colors of Panama
